### PR TITLE
Fix github actions build

### PR DESCRIPTION
**Pull request by elijahr2411**
Changes the command to set environment variables to `$GITHUB_ENV` as `set-env` was disabled by GitHub due to a vulnerability.

I'll mark it as ready for review when my build finishes so I know it builds successfully.

### CODE REVIEW

**Comment by Weissnix4711** [comment]
*We know*

**Comment by elijahr2411** [comment]
@Weissnix4711 
huh? I'm really confused as to what you meant.

**Comment by Weissnix4711** [comment]
Nvm. I thought you hadn't seen mine and exto's forks yet, and I was trying to stop you from trying to figure out stuff we had already.

**Comment by elijahr2411** [comment]
Ohhhhhhhh. You’re right, I haven’t until a few minutes ago when I saw your PR on my fork. Thanks

**Pull request closed without merging**
